name: Build Once Time

env:
  ZIG_VERSION: master
  NIM_VERSION: binary:stable
  REGISTRY: docker.io
  IMAGENAME: initdc/nim-demo

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency: 
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set zig version  
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ env.ZIG_VERSION }}
      - name: Set nim version
        uses: iffy/install-nim@v4
        with:
          version: ${{ env.NIM_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract Docker metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGENAME }}   
      - name: Set RELEASE_VERSION
        run: |
          set -e
          
          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo RELEASE_VERSION="${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: Build release
        run: ruby build.rb ${RELEASE_VERSION}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "upload/*"
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "upload/*"
      - name: Build and push Docker image
        run: ruby docker-tag.rb ${RELEASE_VERSION}
