name: Merge or Pull requests

env:
  ZIG_VERSION: master
  NIM_VERSION: binary:stable

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'next'
  pull_request:

concurrency: 
  group: ${{ github.sha }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set zig version
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ env.ZIG_VERSION }}
      - name: Set nim version
        uses: iffy/install-nim@v4
        with:
          version: ${{ env.NIM_VERSION }}
      - name: Build Artifact
        run: |
          ruby build.rb --install-cc
          ruby build.rb test --run-test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "upload/*"
